"""empty message

Revision ID: 05d857f4b393
Revises: 72efca35e892
Create Date: 2016-08-07 05:03:21.971989

"""

# revision identifiers, used by Alembic.
revision = '05d857f4b393'
down_revision = '72efca35e892'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebay_product', sa.Column('times_clicked', sa.Integer(), nullable=True))
    op.add_column('ebay_product', sa.Column('times_suggested', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebay_product', 'times_suggested')
    op.drop_column('ebay_product', 'times_clicked')
    ### end Alembic commands ###
