"""empty message

Revision ID: 72efca35e892
Revises: None
Create Date: 2016-08-07 03:25:39.932713

"""

# revision identifiers, used by Alembic.
revision = '72efca35e892'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('personality_data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_product_product_id'), 'ebay_product', ['product_id'], unique=True)
    op.create_table('twitter_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('personality_data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_user_user_id'), 'twitter_user', ['user_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_user_user_id'), table_name='twitter_user')
    op.drop_table('twitter_user')
    op.drop_index(op.f('ix_ebay_product_product_id'), table_name='ebay_product')
    op.drop_table('ebay_product')
    ### end Alembic commands ###
