"""empty message

Revision ID: c0d2d1d641b3
Revises: 05d857f4b393
Create Date: 2016-08-07 07:13:49.292292

"""

# revision identifiers, used by Alembic.
revision = 'c0d2d1d641b3'
down_revision = '05d857f4b393'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebay_product', sa.Column('product_img_link', sa.String(), nullable=True))
    op.add_column('ebay_product', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('ebay_product', sa.Column('product_price', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebay_product', 'product_price')
    op.drop_column('ebay_product', 'product_name')
    op.drop_column('ebay_product', 'product_img_link')
    ### end Alembic commands ###
