"""empty message

Revision ID: e057eaa00624
Revises: c0d2d1d641b3
Create Date: 2016-08-07 07:16:59.416860

"""

# revision identifiers, used by Alembic.
revision = 'e057eaa00624'
down_revision = 'c0d2d1d641b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebay_product', sa.Column('product_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebay_product', 'product_url')
    ### end Alembic commands ###
